### PR TITLE
[issue-344] Fix custom function conflicts across regions

### LINKED ISSUE #344: Holidays with identical names can return incorrect results based on order in which regions are loaded
## Expected Behavior

The holiday 'Corpus Christi' for the `co` region should be returned when querying for `2014-06-23` even if other regions _also_ containing a 'Corpus Christi' holiday are loaded first.

Expected correct output while loading `br` region before `co` region:

```ruby
~/Code/ppeble/holidays(master ✗) make console
bundle exec rake console
irb -r rubygems -I lib -r holidays.rb
irb(main):001:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> []
irb(main):002:0> Holidays.on(Date.civil(2014, 6, 19), :br)
=> [{:date=>#<Date: 2014-06-19 ((2456828j,0s,0n),+0s,2299161j)>, :name=>"Corpus Christi", :regions=>[:br]}]
irb(main):003:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> [:br]
irb(main):004:0> Holidays.on(Date.civil(2014, 6, 23), :co)
=> [{:date=>#<Date: 2014-06-23 ((2456832j,0s,0n),+0s,2299161j)>, :name=>"Corpus Christi", :regions=>[:co]}]
irb(main):005:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> [:br, :co]
```

## Current Behavior

Loading the `br` region first means that the correct definition for `co` is not used, resulting in `2014-06-23` returning nothing.

```ruby
~/Code/ppeble/holidays(master ✗) make console
bundle exec rake console
irb -r rubygems -I lib -r holidays.rb
irb(main):001:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> []
irb(main):002:0> Holidays.on(Date.civil(2014, 6, 19), :br)
=> [{:date=>#<Date: 2014-06-19 ((2456828j,0s,0n),+0s,2299161j)>, :name=>"Corpus Christi", :regions=>[:br]}]
irb(main):003:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> [:br]
irb(main):004:0> Holidays.on(Date.civil(2014, 6, 23), :co)
=> []
irb(main):005:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> [:br, :co]
```

## Detailed Description

This specific scenario was found via the [PR to fix Colombian holidays](https://github.com/holidays/definitions/pull/132) and only presents itself using the updates in that PR. However this behavior would exist in any other similar scenario.

The issue in this ruby implementation is that the `co` and `br` regions both have an entry named `Corpus Christi` but they have different logic:

Colombia:

```yaml
- name: Corpus Christi
   regions: [co]
   function: easter(year)
   function_modifier: 64
```

Brazil:

```yaml
- name: Corpus Christi
   regions: [br]
   function: easter(year)
   function_modifier: 60
```

### PR DESCRIPTION
**Pull request by ppeble**
Fixes [issue-344](https://github.com/holidays/holidays/issues/344)

### Summary

When two regions define a holiday using the same custom function name but different implementations, querying both regions simultaneously would only evaluate one region's function, which was whatever one was loaded first. The other region's result was silently dropped

I have added new tests that cover these scenarios and the existing tests still pass. That should give confidence that we are safe.

### Details

The following has changed:

* search context
* merger context
* custom methods in-memory repository

The basic gist is that we now keep track on a per-region basis for custom functions so that we can appropriately apply them. I have added integration tests that will confirm this behavior. I also have tests specifically for the situation I laid out in the original issue.,

### Personal Story

This has been a literal thorn in my side since 2019.

I don't want to get too personal but in 2019 when I wrote the 344 issue I had one child and another on the way. I now have 3 kids. Over the last few years I kept this TODO on my radar. It may mean nothing to most but I had a TODO on my personal list that I literally moved forward one or two months at a time for years. It was a constant reminder that I was not giving this enough attention.

Ultimately this is not a super complicated problem. I just never had the motivation to really sit down and concentrate. I am hoping that now that my youngest is nearing school age that I can give this project and its related ones the appropriate amount of attention.

I truly appreciate that everyone who relies on this project has not flooded me with vitriol. The story of this gem is a very human one. :heart:

### CODE REVIEW

**Comment by ppeble** [comment]
@ttwo32 @gregoryfm Please review this and let me know what you think!

I very much want it to be that  we have multiple people that can review and contribute. :heart: 

Anyone else that wants to give opinions, please do. We are open for outside contribution. We would welcome anyone that wants to be a part of this gem. :bow:

**Review by DagonWat — COMMENTED** [review]
Hi @ppeble, awesome work!

I wanted to start investing more time into this gem, I dropped you an email on that topic recently,

I just wanted to test it locally and for some reason the expected behavior already mets the requirement:

```
irb(main):001> Holidays::Factory::Definition.regions_repository.all_loaded
=> []
irb(main):002> Holidays.on(Date.civil(2014, 6, 19), :br)
irb(main):003> 
=> [{date: #<Date: 2014-06-19 ((2456828j,0s,0n),+0s,2299161j)>, name: "Corpus Christi", regions: [:br]}]
irb(main):004> Holidays::Factory::Definition.regions_repository.all_loaded
=> [:br]
irb(main):005> Holidays.on(Date.civil(2014, 6, 23), :co)
irb(main):006> 
=> [{date: #<Date: 2014-06-23 ((2456832j,0s,0n),+0s,2299161j)>, name: "Corpus Christi", regions: [:co]}]
irb(main):007> 
```

How can I test whats broken atm?

**Comment by ppeble** [comment]
I was not aware of this! When I ran the tests I wrote before it seemed to still be there. It's possible that the definitions were changed to avoid this specific issue, but the overall issue still persists.

Let me dig into it tonight and I'll give you a concrete example.

**Comment by ppeble** [comment]
Ah, I see now! There are two things here:

* the original `br`/`co` scenario _was_ already fixed in https://github.com/holidays/holidays/pull/346. That's why it appears to work.
* however, during my research I found that the problem ran deeper than this one fix, that is what this PR is addressing

I had completely forgotten about the previous PR!

To test out the scenario that my change is addressing then try this on `master`:

```
require 'holidays'

Holidays.load_custom('test/data/test_multiple_regions_with_conflicts_region_1.yaml')

result = Holidays.on(Date.new(2019, 9, 1), :multiple_with_conflict_1)
puts 'Region 1 (Sept 1, expect 1 result): ' + result.inspect

Holidays.load_custom('test/data/test_multiple_regions_with_conflicts_region_2.yaml')

result = Holidays.on(Date.new(2019, 11, 1), :multiple_with_conflict_2)
puts 'Region 2 (Nov 1, expect 1 result): ' + result.inspect

# Region 1 must still return Sept 1 — returns [] on master (the bug)
result = Holidays.on(Date.new(2019, 9, 1), :multiple_with_conflict_1)
puts 'Region 1 again (Sept 1, expect 1 result): ' + result.inspect
```

This should return:

```
Region 1 (Sept 1, expect 1 result): [{date: #<Date: 2019-09-01 ((2458728j,0s,0n),+0s,2299161j)>, name: "With Function Only Same Function Name", regions: [:multiple_with_conflict_1]}]
Region 2 (Nov 1, expect 1 result): [{date: #<Date: 2019-11-01 ((2458789j,0s,0n),+0s,2299161j)>, name: "With Function Only Same Function Name", regions: [:multiple_with_conflict_1, :multiple_with_conflict_2]}]
Region 1 again (Sept 1, expect 1 result): []
```

This is the scenario that is being fixed, explicitly, by this change. You can see that this fix attempts to cover _all_ of the various scenarios of custom method conflicts, whereas before it fixed the issue at hand but not everything.

Thank you for keeping me honest.

File: test/coverage_report.rb [hunk 1]
```diff
@@ -2,7 +2,7 @@
 
 # JRuby coverage reporting is inaccurate without --debug mode, resulting in
 # artificially low numbers. Skip the minimum coverage check under JRuby.
-SimpleCov.minimum_coverage 89 unless RUBY_PLATFORM == 'java'
+SimpleCov.minimum_coverage 93 unless RUBY_PLATFORM == 'java'
```
Comment (ttwo32) [inline test/coverage_report.rb]: Wow, Great. 👍

File: test/e2e/test_multiple_regions_with_conflict.rb [hunk 2]
```diff
@@ -24,6 +23,163 @@ def test_custom_loaded_region_returns_correct_value_with_function_modifier_confl
...
+    assert_equal 'With Function Only Same Function Name', result.first[:name]
+
+    # Region 1 must still return the correct date even though region 2 was
+    # loaded afterwards with the same function name but different logic.
+    result = Holidays.on(Date.new(2019, 9, 1), :multiple_with_conflict_1)
+    assert_equal 1, result.count
+    assert_equal 'With Function Only Same Function Name', result.first[:name]
+  end
+
+  # Load region 2 first, then region 1, which is the opposite of the test above.
```
Comment (ttwo32) [inline test/e2e/test_multiple_regions_with_conflict.rb:54]: I like this test. 😍

**Review by ttwo32 — DISMISSED** [review]
Hi Phil,

Great job on this! I’ve reviewed the changes and confirmed that all the tests pass perfectly on my end. It’s really satisfying to see this long-standing TODO finally crossed off. 👍

One thing I noticed while reviewing: we have tests for conflicts between two regions, but I didn't see any test cases for when three or more regions have the same function name conflict. The current implementation looks solid enough to handle it, but do you think it's worth adding a test case for 3+ regions just to be 100% sure?

**Review by DagonWat — APPROVED** [review]
As far as I know the codebase - changes look good!

**Comment by ppeble** [comment]
Thank you both! I have pushed updates.

> One thing I noticed while reviewing: we have tests for conflicts between two regions, but I didn't see any test cases for when three or more regions have the same function name conflict. The current implementation looks solid enough to handle it, but do you think it's worth adding a test case for 3+ regions just to be 100% sure?

I have added the 3 region test for clarity. Let me know what you think.

**Review by ttwo32 — DISMISSED** [review]
LGTM! Thanks, Phil 👍

**Comment by ppeble** [comment]
@ttwo32 I apologize, I was actively updating this because of changes I made for splitting the tests up.  See https://github.com/holidays/definitions/pull/327 and https://github.com/holidays/holidays/pull/454 for details.

In the end nothing really changed, I only made what I think are clearer testing structures. Sorry for bugging you again for approval!

**Comment by ppeble** [comment]
I am going to force this through, mainly because @ttwo32 already approved twice despite my changes just being rebases. The logic is approved and I'll push forward.
